#
#   ServerSpy
#   by InfinityAtom
#
#   ServerSpy is licenced under the Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
#
#   You are free to:
#   Share — copy and redistribute the material in any medium or format for any purpose, even commercially.
#   The licensor cannot revoke these freedoms as long as you follow the license terms.
#
#   Under the following terms:
#   Attribution — You must give appropriate credit, provide a link to the license,
#   and indicate if changes were made. You may do so in any reasonable manner, but
#   not in any way that suggests the licensor endorses you or your use.
#   NoDerivatives — If you remix, transform, or build upon the material,
#   you may not distribute the modified material.
#
#   A full copy of the licence is available at https://creativecommons.org/licenses/by-nd/4.0/
#


# Enter the bot token from the Discord Developer Portal [STRING]
bot-token: "00000000000000000000000000000000000000000000000000000000000"

# Put in the channel ID for the output chat channel [STRING]
chat-channel-id: "0000000000000000000"

# Enter the channel ID for the console channel [STRING]
console-channel-id: "0000000000000000000"